"""
Version information for Tekmera CLI.
This file is automatically generated during the build process.
For development, version is read from git tags.
"""
import subprocess
import sys
from pathlib import Path


def _get_version_from_git():
    """Get version from git tags for development."""
    try:
        # Try to get latest tag
        result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            cwd=Path(__file__).parent.parent.parent,
            capture_output=True,
            text=True,
            timeout=5
        )
        if result.returncode == 0:
            tag = result.stdout.strip()
            return tag.lstrip('v') if tag.startswith('v') else tag
    except (subprocess.SubprocessError, subprocess.TimeoutExpired, FileNotFoundError):
        pass
    
    # Fallback to development version
    return "0.0.0-dev"


# Development defaults - CI will override these
__version__ = _get_version_from_git()
__build_date__ = "dev"
__commit__ = "dev"
__platform__ = "dev"


def get_version_info():
    """Get comprehensive version information."""
    return {
        "version": __version__,
        "build_date": __build_date__,
        "commit": __commit__,
        "platform": __platform__,
    }


def get_version_string():
    """Get a formatted version string for display."""
    if __build_date__ == "dev":
        return f"{__version__} (development)"
    return f"{__version__} (built {__build_date__})"
